// Üniversite listesi (YÖK'e kayıtlı devlet ve vakıf üniversiteleri + KKTC'deki başlıca üniversiteler).
// Not: Liste elle derlendi; yayına çıkmadan önce YÖK Atlas'taki güncel listeyle karşılaştırılmalı.
// Değer olarak üniversitenin adı saklanır. Kampüs karşılaştırması (sonraki adım) da bu adı kullanacak.

export const UNIVERSITY_OTHER = '__other__';

export const UNIVERSITIES: string[] = [
  // ---- Devlet üniversiteleri ----
  'Abdullah Gül Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Adıyaman Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Akdeniz Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Amasya Üniversitesi',
  'Anadolu Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Müzik ve Güzel Sanatlar Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Ardahan Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Atatürk Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bingöl Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Dicle Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Harran Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
  'Hitit Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Üniversitesi-Cerrahpaşa',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Katip Çelebi Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'Kafkas Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kayseri Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kocaeli Üniversitesi',
  'Konya Teknik Üniversitesi',
  'Kütahya Dumlupınar Üniversitesi',
  'Kütahya Sağlık Bilimleri Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Manisa Celal Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Marmara Üniversitesi',
  'Mersin Üniversitesi',
  'Milli Savunma Üniversitesi',
  'Mimar Sinan Güzel Sanatlar Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Necmettin Erbakan Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Pamukkale Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sağlık Bilimleri Üniversitesi',
  'Sakarya Uygulamalı Bilimler Üniversitesi',
  'Sakarya Üniversitesi',
  'Samsun Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Bilim ve Teknoloji Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Süleyman Demirel Üniversitesi',
  'Şırnak Üniversitesi',
  'Tarsus Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Trabzon Üniversitesi',
  'Trakya Üniversitesi',
  'Türk-Alman Üniversitesi',
  'Türk-Japon Bilim ve Teknoloji Üniversitesi',
  'Uşak Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yalova Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',

  // ---- Vakıf üniversiteleri ----
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
  'Alanya Üniversitesi',
  'Altınbaş Üniversitesi',
  'Ankara Bilim Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Antalya Belek Üniversitesi',
  'Antalya Bilim Üniversitesi',
  'Atılım Üniversitesi',
  'Avrasya Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Başkent Üniversitesi',
  'Beykoz Üniversitesi',
  'Bezmialem Vakıf Üniversitesi',
  'Biruni Üniversitesi',
  'Çağ Üniversitesi',
  'Çankaya Üniversitesi',
  'Demiroğlu Bilim Üniversitesi',
  'Doğuş Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'Haliç Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Işık Üniversitesi',
  'İbn Haldun Üniversitesi',
  'İhsan Doğramacı Bilkent Üniversitesi',
  'İstanbul 29 Mayıs Üniversitesi',
  'İstanbul Arel Üniversitesi',
  'İstanbul Atlas Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Beykent Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'İstanbul Galata Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'İstanbul Medipol Üniversitesi',
  'İstanbul Nişantaşı Üniversitesi',
  'İstanbul Okan Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İstanbul Sağlık ve Teknoloji Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İstanbul Topkapı Üniversitesi',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstinye Üniversitesi',
  'İzmir Ekonomi Üniversitesi',
  'İzmir Tınaztepe Üniversitesi',
  'Kadir Has Üniversitesi',
  'Kapadokya Üniversitesi',
  'Koç Üniversitesi',
  'Kocaeli Sağlık ve Teknoloji Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Lokman Hekim Üniversitesi',
  'Maltepe Üniversitesi',
  'MEF Üniversitesi',
  'Mudanya Üniversitesi',
  'Nuh Naci Yazgan Üniversitesi',
  'Ostim Teknik Üniversitesi',
  'Özyeğin Üniversitesi',
  'Piri Reis Üniversitesi',
  'Sabancı Üniversitesi',
  'Sanko Üniversitesi',
  'TED Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'Toros Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Ufuk Üniversitesi',
  'Üsküdar Üniversitesi',
  'Yaşar Üniversitesi',
  'Yeditepe Üniversitesi',
  'Yüksek İhtisas Üniversitesi',

  // ---- KKTC ----
  'Doğu Akdeniz Üniversitesi',
  'Girne Amerikan Üniversitesi',
  'Lefke Avrupa Üniversitesi',
  'Orta Doğu Teknik Üniversitesi Kuzey Kıbrıs Kampusu',
  'Uluslararası Kıbrıs Üniversitesi',
  'Yakın Doğu Üniversitesi',
];

// Kısaltma ve yaygın adlarla arama (ör. "odtü", "itü", "bilkent")
const ALIASES: Record<string, string[]> = {
  'Orta Doğu Teknik Üniversitesi': ['odtu', 'metu'],
  'Orta Doğu Teknik Üniversitesi Kuzey Kıbrıs Kampusu': ['odtu kkk', 'metu ncc'],
  'İstanbul Teknik Üniversitesi': ['itu'],
  'Yıldız Teknik Üniversitesi': ['ytu'],
  'Karadeniz Teknik Üniversitesi': ['ktu'],
  'Gebze Teknik Üniversitesi': ['gtu'],
  'Boğaziçi Üniversitesi': ['bogazici', 'bou'],
  'İhsan Doğramacı Bilkent Üniversitesi': ['bilkent'],
  'Dokuz Eylül Üniversitesi': ['deu'],
  'İzmir Yüksek Teknoloji Enstitüsü': ['iyte'],
  'TOBB Ekonomi ve Teknoloji Üniversitesi': ['etu', 'tobb etu'],
  'Mimar Sinan Güzel Sanatlar Üniversitesi': ['msgsu', 'mimar sinan'],
  'Eskişehir Osmangazi Üniversitesi': ['ogu', 'esogu'],
  'Ankara Yıldırım Beyazıt Üniversitesi': ['aybu'],
  'Ankara Hacı Bayram Veli Üniversitesi': ['hbv'],
  'Bursa Uludağ Üniversitesi': ['uludag'],
  'İstanbul Üniversitesi-Cerrahpaşa': ['iuc', 'cerrahpasa'],
  'İstanbul Üniversitesi': ['iu'],
  'Marmara Üniversitesi': ['marun'],
  'Ondokuz Mayıs Üniversitesi': ['omu', '19 mayis'],
  'Kahramanmaraş Sütçü İmam Üniversitesi': ['ksu'],
  'Süleyman Demirel Üniversitesi': ['sdu'],
  'Recep Tayyip Erdoğan Üniversitesi': ['rteu'],
  'Çanakkale Onsekiz Mart Üniversitesi': ['comu', '18 mart'],
  'Bolu Abant İzzet Baysal Üniversitesi': ['aibu', 'abant'],
  'Doğu Akdeniz Üniversitesi': ['dau', 'emu'],
  'Yakın Doğu Üniversitesi': ['ydu', 'neu'],
  'Girne Amerikan Üniversitesi': ['gau'],
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi': ['acibadem'],
  'Koç Üniversitesi': ['koc', 'ku'],
  'Sabancı Üniversitesi': ['sabanci', 'su'],
};

// Türkçe karakterlerden bağımsız arama: "bogazici" → "Boğaziçi" bulur
export function foldTr(s: string): string {
  return s
    .toLocaleLowerCase('tr-TR')
    .replace(/[ıîì]/g, 'i')
    .replace(/ğ/g, 'g')
    .replace(/[üû]/g, 'u')
    .replace(/ş/g, 's')
    .replace(/[öô]/g, 'o')
    .replace(/ç/g, 'c')
    .replace(/[âà]/g, 'a')
    .replace(/[-_.,]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const INDEX = UNIVERSITIES.map((name) => ({
  name,
  folded: foldTr(name),
  aliases: (ALIASES[name] ?? []).map(foldTr),
}));

export function searchUniversities(query: string): string[] {
  const q = foldTr(query);
  if (!q) return [...UNIVERSITIES].sort((a, b) => a.localeCompare(b, 'tr-TR'));
  const scored: { name: string; score: number }[] = [];
  for (const u of INDEX) {
    let score = -1;
    if (u.aliases.some((a) => a === q)) score = 0;
    else if (u.folded.startsWith(q)) score = 1;
    else if (u.aliases.some((a) => a.startsWith(q))) score = 2;
    else if (u.folded.split(' ').some((w) => w.startsWith(q))) score = 3;
    else if (u.folded.includes(q)) score = 4;
    if (score >= 0) scored.push({ name: u.name, score });
  }
  return scored
    .sort((a, b) => a.score - b.score || a.name.localeCompare(b.name, 'tr-TR'))
    .map((x) => x.name);
}
